"""empty message

Revision ID: 0a2a9afc69b3
Revises: 5c2a981f2a26
Create Date: 2022-05-05 18:03:32.489757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a2a9afc69b3'
down_revision = '5c2a981f2a26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    # ### end Alembic commands ###
