"""empty message

Revision ID: 5c2a981f2a26
Revises: 687be023d532
Create Date: 2022-05-05 14:23:38.111614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2a981f2a26'
down_revision = '687be023d532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('artists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('artists', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cities', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cities', 'state_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.alter_column('states', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.create_index(op.f('ix_states_name'), 'states', ['name'], unique=False)
    op.alter_column('venues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('venues', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('venues', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venues', 'address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('venues', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('venues', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_states_name'), table_name='states')
    op.alter_column('states', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.alter_column('cities', 'state_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cities', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('artists', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('artists', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
